contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os

work-dir: /app

paths:
  - path: /app
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755

accounts:
  run-as: nonroot
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      shell: /bin/sh

archs:
  - x86_64
  - arm64
  #- arm/v6
  #- arm/v7
